export const doctorColumns = [
    { field: 'id', headerName: 'ID', width: 70 },
    {
        field: 'doctor', headerName: 'Doctor', width: 400,
        renderCell: (params) => {
            return (
                <div className="cellWithImg">
                    <img src={params.row.doctorPhotoUrl} alt="" className="cellImg" />
                    {params.row.doctorName}
                </div>
            )
        }
    }
];

export const doctorRows = [
    {
        id: 0,
        name: "",
        image: "",
        hospital: "",
        speciality: "",
        medical_field: "",
        location: "",
        degree: "",
        consultation_days: "",
        consultation_time: "",
        fees: "",
        contact: "",
        email: ""
    },
    {
        id: 1,
        name: "Dr. Shafayet Karim",
        image: "/Images/doctor1.jpg",
        hospital: "Sir Salimullah Medical College",
        speciality: "Neurologist, Neurosurgeon, Neuropsychiatrist",
        medical_field: "Neurology",
        location: "Dhaka",
        degree: "MBBS, MD (Neurology)",
        consultation_days: ["Monday", "Wednesday", "Friday"],
        consultation_time: "9:00 AM - 12:00 PM",
        fees: "1000 BDT",
        contact: "017XXXXXXXX",
        email: "shafayet.karim@example.com"
    },
    {
        id: 2,
        name: "Dr. Sadia Noor",
        image: "/Images/doctor2.jpg",
        hospital: "Dhaka Medical College",
        speciality: "Gynecologist, Perinatologist, Gynecologic Oncologist",
        medical_field: "Gynecology",
        location: "Dhaka",
        degree: "MBBS, MD (Gynecology)",
        consultation_days: ["Tuesday", "Thursday", "Saturday"],
        consultation_time: "10:00 AM - 1:00 PM",
        fees: "1200 BDT",
        contact: "017XXXXXXXX",
        email: "sadia.noor@example.com"
    },
    {
        id: 3,
        name: "Dr. Zubair Rahman",
        image: "/Images/doctor3.jpg",
        hospital: "Chittagong Medical College",
        speciality: "Cardiologist, Electrophysiologist, Cardiothoracic Surgeon",
        medical_field: "Cardiology",
        location: "Chittagong",
        degree: "MBBS, FCPS (Cardiology)",
        consultation_days: ["Monday", "Wednesday", "Friday"],
        consultation_time: "11:00 AM - 2:00 PM",
        fees: "1500 BDT",
        contact: "017XXXXXXXX",
        email: "zubair.rahman@example.com"
    },
    {
        id: 4,
        name: "Dr. Nayeem Islam",
        image: "/Images/doctor4.jpg",
        hospital: "Rajshahi Medical College",
        speciality: "Ophthalmologist, Neuro-ophthalmologist, Optometrist",
        medical_field: "Ophthalmology",
        location: "Rajshahi",
        degree: "MBBS, MS (Ophthalmology)",
        consultation_days: ["Sunday", "Tuesday", "Thursday"],
        consultation_time: "9:00 AM - 12:00 PM",
        fees: "800 BDT",
        contact: "017XXXXXXXX",
        email: "nayeem.islam@example.com"
    },
    {
        id: 5,
        name: "Dr. Anika Sultana",
        image: "/Images/doctor5.jpg",
        hospital: "Mymensingh Medical College",
        speciality: "Pediatrician, Pediatric Surgeon, Neonatologist",
        medical_field: "Pediatrics",
        location: "Mymensingh",
        degree: "MBBS, MD (Pediatrics)",
        consultation_days: ["Monday", "Wednesday", "Friday"],
        consultation_time: "10:00 AM - 1:00 PM",
        fees: "900 BDT",
        contact: "017XXXXXXXX",
        email: "anika.sultana@example.com"
    },
    {
        id: 6,
        name: "Dr. Rina Roy",
        image: "/Images/female-doctor.jpg",
        hospital: "Sylhet MAG Osmani Medical College",
        speciality: "Dermatologist, Trichologist, Cosmetologist",
        medical_field: "Dermatology",
        location: "Sylhet",
        degree: "MBBS, MD (Dermatology)",
        consultation_days: ["Tuesday", "Thursday", "Saturday"],
        consultation_time: "2:00 PM - 5:00 PM",
        fees: "1000 BDT",
        contact: "017XXXXXXXX",
        email: "rina.roy@example.com"
    },
    {
        id: 7,
        name: "Dr. Omar Khan",
        image: "/Images/male-doctor.jpg",
        hospital: "Bangladesh Medical College",
        speciality: "Orthopedic Surgeon, Sports Medicine Specialist",
        medical_field: "Orthopedics",
        location: "Dhaka",
        degree: "MBBS, MS (Orthopedics)",
        consultation_days: ["Monday", "Wednesday", "Friday"],
        consultation_time: "8:00 AM - 11:00 AM",
        fees: "1300 BDT",
        contact: "017XXXXXXXX",
        email: "omar.khan@example.com"
    },
    {
        id: 8,
        name: "Dr. Fahim Hossain",
        image: "/Images/male-doctor.jpg",
        hospital: "Combined Military Hospital Dhaka",
        speciality: "Urologist, Kidney Specialist",
        medical_field: "Urology",
        location: "Dhaka",
        degree: "MBBS, FCPS (Urology)",
        consultation_days: ["Tuesday", "Thursday", "Saturday"],
        consultation_time: "10:00 AM - 1:00 PM",
        fees: "1400 BDT",
        contact: "017XXXXXXXX",
        email: "fahim.hossain@example.com"
    },
    {
        id: 9,
        name: "Dr. Tasnim Islam",
        image: "/Images/female-doctor.jpg",
        hospital: "Chittagong Medical College",
        speciality: "General Surgeon, Laparoscopic Surgeon",
        medical_field: "Surgery",
        location: "Chittagong",
        degree: "MBBS, MS (Surgery)",
        consultation_days: ["Monday", "Wednesday", "Friday"],
        consultation_time: "9:00 AM - 12:00 PM",
        fees: "1100 BDT",
        contact: "017XXXXXXXX",
        email: "tasnim.islam@example.com"
    },
    {
        id: 10,
        name: "Dr. Monira Begum",
        image: "/Images/female-doctor.jpg",
        hospital: "Kuwait Bangladesh Friendship Government Hospital",
        speciality: "Endocrinologist, Diabetes Specialist",
        medical_field: "Endocrinology",
        location: "Dhaka",
        degree: "MBBS, MD (Endocrinology)",
        consultation_days: ["Sunday", "Tuesday", "Thursday"],
        consultation_time: "8:00 AM - 11:00 AM",
        fees: "1200 BDT",
        contact: "017XXXXXXXX",
        email: "monira.begum@example.com"
    },
    {
        id: 11,
        name: "Dr. Kamal Ahmed",
        image: "/Images/male-doctor.jpg",
        hospital: "Dhaka National Medical College Hospital",
        speciality: "Pulmonologist, Sleep Disorder Specialist",
        medical_field: "Pulmonology",
        location: "Dhaka",
        degree: "MBBS, MD (Pulmonology)",
        consultation_days: ["Monday", "Wednesday", "Friday"],
        consultation_time: "2:00 PM - 5:00 PM",
        fees: "1500 BDT",
        contact: "017XXXXXXXX",
        email: "kamal.ahmed@example.com"
    },
    {
        id: 12,
        name: "Dr. Syeda Roksana",
        image: "/Images/female-doctor.jpg",
        hospital: "Rajshahi Medical College",
        speciality: "Hematologist, Cancer Specialist",
        medical_field: "Hematology",
        location: "Rajshahi",
        degree: "MBBS, MD (Hematology)",
        consultation_days: ["Tuesday", "Thursday", "Saturday"],
        consultation_time: "9:00 AM - 12:00 PM",
        fees: "1000 BDT",
        contact: "017XXXXXXXX",
        email: "syeda.roksana@example.com"
    },
    {
        id: 13,
        name: "Dr. Mahmudul Hasan",
        image: "/Images/male-doctor.jpg",
        hospital: "Siddique Medical College",
        speciality: "Rheumatologist, Immunologist",
        medical_field: "Rheumatology",
        location: "Dhaka",
        degree: "MBBS, MD (Rheumatology)",
        consultation_days: ["Monday", "Wednesday", "Friday"],
        consultation_time: "9:00 AM - 12:00 PM",
        fees: "1000 BDT",
        contact: "017XXXXXXXX",
        email: "mahmudul.hasan@example.com"
    },
    {
        id: 14,
        name: "Dr. Shima Ahmed",
        image: "/Images/female-doctor.jpg",
        hospital: "United Hospital Limited",
        speciality: "Gastroenterologist, Hepatologist",
        medical_field: "Gastroenterology",
        location: "Dhaka",
        degree: "MBBS, MD (Gastroenterology)",
        consultation_days: ["Monday", "Wednesday", "Friday"],
        consultation_time: "10:00 AM - 1:00 PM",
        fees: "1400 BDT",
        contact: "017XXXXXXXX",
        email: "shima.ahmed@example.com"
    },
    {
        id: 15,
        name: "Dr. Ashraful Islam",
        image: "/Images/male-doctor.jpg",
        hospital: "Bangladesh Medical College",
        speciality: "Psychiatrist, Mental Health Expert",
        medical_field: "Psychiatry",
        location: "Dhaka",
        degree: "MBBS, MD (Psychiatry)",
        consultation_days: ["Sunday", "Tuesday", "Thursday"],
        consultation_time: "2:00 PM - 5:00 PM",
        fees: "1200 BDT",
        contact: "017XXXXXXXX",
        email: "ashraful.islam@example.com"
    }
];