export const appointments = [
  {
    appointmentToken: 1,
    patientName: "Patient E",
    patientDob: "2000-12-20",
    patientPhone: "01234567890",
    patientEmail: "patientb@example.com",
    patientGender: "Female",
    reasonForVisit: "Having fever for the past 7 days",
    visitDay: "Friday",
    appointmentBy: "Fahim",
    appointmentDate: "2025-07-18"
  },
  {
    appointmentToken: 2,
    patientName: "Patient A",
    patientDob: "1995-05-10",
    patientPhone: "01700000001",
    patientEmail: "patienta@example.com",
    patientGender: "Male",
    reasonForVisit: "Chest pain and breathing issues",
    visitDay: "Monday",
    appointmentBy: "Rafi",
    appointmentDate: "2025-07-07"
  },
  {
    appointmentToken: 3,
    patientName: "Patient B",
    patientDob: "1988-08-25",
    patientPhone: "01811111122",
    patientEmail: "patientb@example.com",
    patientGender: "Male",
    reasonForVisit: "Routine health check-up",
    visitDay: "Wednesday",
    appointmentBy: "Mitu",
    appointmentDate: "2025-07-16"
  },
  {
    appointmentToken: 4,
    patientName: "Patient C",
    patientDob: "2002-03-15",
    patientPhone: "01922222233",
    patientEmail: "patientc@example.com",
    patientGender: "Female",
    reasonForVisit: "Stomach ache and nausea",
    visitDay: "Friday",
    appointmentBy: "Tushar",
    appointmentDate: "2025-07-11"
  },
  {
    appointmentToken: 5,
    patientName: "Patient D",
    patientDob: "1979-11-30",
    patientPhone: "01633333344",
    patientEmail: "patientd@example.com",
    patientGender: "Male",
    reasonForVisit: "Follow-up on blood pressure medication",
    visitDay: "Sunday",
    appointmentBy: "Lamia",
    appointmentDate: "2025-07-20"
  },

  // 🔽 Additional past appointments (multiple on same days)
  {
    appointmentToken: 6,
    patientName: "Patient F",
    patientDob: "1990-02-14",
    patientPhone: "01744445555",
    patientEmail: "patientf@example.com",
    patientGender: "Female",
    reasonForVisit: "Skin rash and itching",
    visitDay: "Wednesday",
    appointmentBy: "Fahim",
    appointmentDate: "2025-07-09"
  },
  {
    appointmentToken: 7,
    patientName: "Patient G",
    patientDob: "1985-07-01",
    patientPhone: "01855556666",
    patientEmail: "patientg@example.com",
    patientGender: "Male",
    reasonForVisit: "Dizziness and fatigue",
    visitDay: "Wednesday",
    appointmentBy: "Mitu",
    appointmentDate: "2025-07-09"
  },
  {
    appointmentToken: 8,
    patientName: "Patient H",
    patientDob: "1992-10-10",
    patientPhone: "01677778888",
    patientEmail: "patienth@example.com",
    patientGender: "Female",
    reasonForVisit: "Blood sugar monitoring",
    visitDay: "Tuesday",
    appointmentBy: "Lamia",
    appointmentDate: "2025-07-08"
  },
  {
    appointmentToken: 9,
    patientName: "Patient I",
    patientDob: "2001-01-01",
    patientPhone: "01799990000",
    patientEmail: "patienti@example.com",
    patientGender: "Male",
    reasonForVisit: "Headache and migraine issues",
    visitDay: "Tuesday",
    appointmentBy: "Tushar",
    appointmentDate: "2025-07-08"
  },
  {
    appointmentToken: 10,
    patientName: "Patient J",
    patientDob: "1998-09-21",
    patientPhone: "01822223333",
    patientEmail: "patientj@example.com",
    patientGender: "Female",
    reasonForVisit: "Post-surgery check-up",
    visitDay: "Monday",
    appointmentBy: "Rafi",
    appointmentDate: "2025-07-07"
  },
    {
    appointmentToken: 11,
    patientName: "Patient K",
    patientDob: "1993-12-11",
    patientPhone: "01788889999",
    patientEmail: "patientk@example.com",
    patientGender: "Male",
    reasonForVisit: "Eye pain and dryness",
    visitDay: "Tuesday",
    appointmentBy: "Fahim",
    appointmentDate: "2025-07-08"
  },
  {
    appointmentToken: 12,
    patientName: "Patient L",
    patientDob: "2003-06-15",
    patientPhone: "01611112222",
    patientEmail: "patientl@example.com",
    patientGender: "Female",
    reasonForVisit: "Routine dental check-up",
    visitDay: "Tuesday",
    appointmentBy: "Lamia",
    appointmentDate: "2025-07-08"
  },
  {
    appointmentToken: 13,
    patientName: "Patient M",
    patientDob: "1980-03-18",
    patientPhone: "01899998888",
    patientEmail: "patientm@example.com",
    patientGender: "Male",
    reasonForVisit: "Back pain and posture check",
    visitDay: "Tuesday",
    appointmentBy: "Mitu",
    appointmentDate: "2025-07-08"
  },
  {
    appointmentToken: 14,
    patientName: "Patient N",
    patientDob: "1999-11-30",
    patientPhone: "01900001111",
    patientEmail: "patientn@example.com",
    patientGender: "Female",
    reasonForVisit: "High blood pressure monitoring",
    visitDay: "Wednesday",
    appointmentBy: "Tushar",
    appointmentDate: "2025-07-09"
  },
  {
    appointmentToken: 15,
    patientName: "Patient O",
    patientDob: "1997-07-07",
    patientPhone: "01544446666",
    patientEmail: "patiento@example.com",
    patientGender: "Male",
    reasonForVisit: "Fatigue and vitamin deficiency",
    visitDay: "Sunday",
    appointmentBy: "Rafi",
    appointmentDate: "2025-07-06"
  },
  {
    appointmentToken: 16,
    patientName: "Patient P",
    patientDob: "1982-02-22",
    patientPhone: "01888880000",
    patientEmail: "patientp@example.com",
    patientGender: "Female",
    reasonForVisit: "Thyroid test follow-up",
    visitDay: "Friday",
    appointmentBy: "Fahim",
    appointmentDate: "2025-07-04"
  },
  {
    appointmentToken: 17,
    patientName: "Patient Q",
    patientDob: "1994-04-04",
    patientPhone: "01712345678",
    patientEmail: "patientq@example.com",
    patientGender: "Male",
    reasonForVisit: "Ankle sprain check-up",
    visitDay: "Sunday",
    appointmentBy: "Lamia",
    appointmentDate: "2025-07-06"
  },
  {
    appointmentToken: 18,
    patientName: "Patient R",
    patientDob: "1986-06-06",
    patientPhone: "01812345678",
    patientEmail: "patientr@example.com",
    patientGender: "Female",
    reasonForVisit: "Ear infection",
    visitDay: "Sunday",
    appointmentBy: "Mitu",
    appointmentDate: "2025-07-06"
  },
  {
    appointmentToken: 19,
    patientName: "Patient S",
    patientDob: "1990-10-10",
    patientPhone: "01912345678",
    patientEmail: "patients@example.com",
    patientGender: "Male",
    reasonForVisit: "Migraine evaluation",
    visitDay: "Tuesday",
    appointmentBy: "Tushar",
    appointmentDate: "2025-07-08"
  },
  {
    appointmentToken: 20,
    patientName: "Patient T",
    patientDob: "1996-01-01",
    patientPhone: "01777778888",
    patientEmail: "patientt@example.com",
    patientGender: "Female",
    reasonForVisit: "General wellness check",
    visitDay: "Tuesday",
    appointmentBy: "Rafi",
    appointmentDate: "2025-07-08"
  }
]
